### ISSUE TITLE
DC2 Milestones

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#47]
To get a sense of what we need to make, and by when, I went through Section 8 of the [DC2 Plan](https://www.overleaf.com/read/jwbjvjnszkzf) (including Katrin's nice schedule figure) and extracted a list of milestones, and put them in Table 7. This table could potentially become part of the Executive Summary  - I think it's something that the WGs would like to see.  

The major milestones are, I think, a DC2 Readiness Review (which we need to do in order to avoid pilot error), and the DC2 Internal Data Release (which we'd like to do _before_ the summer collaboration meeting, to give time for the analysis groups to take a look at the data and present some preliminary results in Pittsburgh). 

Some notes:
* The dates on these milestone are targets, to get us started. We can expect some of them to slip, but not too far...
* The cosmoDC2 extragalactic catalog will not be ready by the time of the winter collaboration meeting, so that will be a bit early for a DC2 Readiness Review. Instead, we could use the collaboration meeting for a readiness _preview_, where we look at the state of the image simulation and DM level 2 pipelines and the cosmoDC2 production. We could also aim to decide on the PhoSim/ImSim balance at that point.
* If the image simulation is orchestrated cleverly, could DM processing start before image production is complete? Seems like it probably could.
* The current schedule has the DC2 DM catalogs finished by 6/8/18, which gives us 6 weeks of schedule contingency before the CMU meeting. In DC1 we used all of our contingency...
* I wasn't sure exactly what was being targeted to have ready before the Sprint Week, or by the end of the Sprint Week, so I made some guesses - these will probably need editing.

@cwwalter @katrinheitmann @fjaviersanchez @jchiang87 @salmanhabib @evevkovacs @SimonKrughoff @rmandelb Can you please take 5 mins to look carefully at these milestones and suggest/make changes? In some cases the dates may not be ideal, the gaps between dates may be sub-optimal, milestones may need breaking into smaller steps, etc. Comments welcome on whether this should be part of the executive summary, too.

If we can agree on what we need to build by when, we can then edit the SRM until it matches this plan: each product in this table should be an SRM deliverable (or a piece of one), I think.

**Comment by katrinheitmann** [comment]
The products for the Sprint week got delayed quite a bit due to CatSim questions. (My understanding had been that CatSim was ready to work on protoDC2 when protoDC2 was delivered but a whole bunch of questions about units etc showed up in the end. Maybe not surprising ... and one reason for the downscaled work!) The idea was to have a small set (2 filters, one year depth or something) done for the sprint week mostly for making sure that (a) all the codes talk to each other correctly, and (b) develop a plan how people will access the data (e.g., they probably want to have the truth information connected to the DM output). I think the validation time is also a little short in the table currently (e.g., for protoDC2 we will need longer than until 5/1 given how few people we currently have that are working on it -- they are mostly from CS, we do need to get more analysis people to look at the catalog as well). In the timeline figure I was more thinking about end of Jan. for the validation.

**Comment by drphilmarshall** [comment]
OK, thanks @katrinheitmann ! I got some feedback from @jchiang87 as well, and have the following list of modifications to make:

* [ ] Set Run 1.0 dates to the end of Sprint Week
* [ ] Allow more time for protoDC2 Extragalactic Catalog validation 
* [ ] Include the Truth Tables to the list of deliverables (to enable validation tests)
* [ ] Add Run 1.1 Instance Catalogs deliverable, and make clear that this should include all required time domain objects
* [ ] Add notes to indicate that instance catalog deliverables need to capture the required cadence and pointing/dithering  information.
* [ ] Elevate the two validation test suites (Extragalactic Catalog, and DM Catalog) to deliverable status (to make sure they get built properly)
* [ ] Define a small test Run 1.9 to be executed between the SSim/CI code freeze and the DC2 RR, to provide meaningful input to the review.
* [ ] Clearly indicate which time domain objects are to be included in each Run

Jim points out that most of these modifications would be good things to talk about in this week's SSim meeting.

**Comment by katrinheitmann** [comment]
Are you going to make those modification? Just checking ... One other 
small question: should we add a p and i for the runs to distinguish 
phosim and imsim rather than tracking the numbers somewhere? So Run-p 
1.1 and Run-i 1.1 would then exist. Just wondering. Thanks!

**Comment by jchiang87** [comment]
Here are a few follow-up comments on the proposed updates to the milestones:

* In my view, the SSim and CI Code freezes should mean that no new development can occur after the freeze date, so that those dates are the drop-deadlines for getting features like handling sensor effects, adjustments to sky background, etc. into the phosim, imsim, or L1/L2 codes.  *Operational* bug-fixes can, of course, be made at any time.

* Items that will require new development (i.e., real work that needs to be issued, scheduled, and assigned):
  * Modify the `generateDc2InstCat.py` script to produce "imsim-style" instance catalogs.  This should be straight-forward, but it nevertheless needs to assigned and implemented.
  * Implement time-varying AGN using the protoDC2 catalog.  We didn't have time to do this before Sprint Week, but this needs to be done before Run 1.1.
  * Extracting Truth Tables from CatSim. We also need to define precisely what we want those truth tables to contain, e.g., top of the atmosphere ugrizy magnitudes, galaxy shape, and WL distortion parameters, etc..  For time varying sources, we need entries for every visit in which they appear, whereas non-varying sources would just need one entry for the full survey.
  * What should be in the validation test suites? At a minimum, this should include running the DM team's QA scripts, but it should also include some set of comparisons between the information in the truth tables and the DM catalog outputs.  We need to define those comparisons precisely and implement scripts to perform them.  We can build upon DC1-related work for this.
  * Pointing location for cosmoDC2 and dithering implementation (including DDF visits). We need to pick a specific location on the sky for the production DC2 catalogs (centered on the Twinkles field seems to be an early contender).  Even if we use the DC1-era dithers for the WFD parts of the survey, we will need new development for the DDF-specific fields.

**Comment by drphilmarshall** [comment]
Yes, I'll make the changes. Also, here's some more feedback from @cwwalter : 
* [ ] Run 1.1 should be a larger-scale test than Run 1.0, and include both PhoSim and ImSim realizations - and be the thing that is _introduced_ to the collaboration at the SLAC meeting and then the test set that determines our readiness for production
* [ ] We should avoid the term "Review" since it implies a level of formality that we don't really need: "checkpoint" is a better term. The checkpoint would still be a meeting where we inspect the results of a well-defined set of tests, and at the end of which a decision to proceed or not is made. 
* [ ] People will need a whole month after the introduction of the Run 1.1 data at the SLAC meeting to do all their validation checks, so the Checkpoint should be around 3/15.
* [ ] It's not obvious that the dates refer to the delivery of a product (rather than the start of a process) - find some way of making this clearer.

@katrinheitmann Good idea to carry a letter marking the image simulation code. Let's keep it with the number, though, so that other things (Tables, etc) can have the same Run ID attached to them. So, Run 1.1p, Run 2.0i etc.

**Comment by katrinheitmann** [comment]
@jchiang87 For the work items still to be done for the extragalactic catalogs, I made a list at the end of Section 5 (5.4) where I just made notes for the team what needs to be done. If you think it's useful, we can do the same for the items you list above. The first three bullets all concern CatSim I believe and so does the last. The validation section has been started in Section 11, maybe we can add the fourth bullet there. Then I definitely would copy your definition of freeze into the timeline section. What do you think?

**Comment by jchiang87** [comment]
Sounds good @katrinheitmann .  I can update section 6 with those tasks if you want.  Regarding the last item in my list, I think the scope is larger than CatSim since there are science implications involved in the sky location of the image sims and the choice needs to be coordinated with the time-domain groups.

**Comment by yymao** [comment]
@katrinheitmann @aphearin will there be a GalSampler version of protoDC2 available for testing in DESCQA *before* the `cosmoDC2 Checkpoint` milestone?

**Comment by katrinheitmann** [comment]
Yes, please go ahead and update section 6 if you don't mind. We should 
find a good way to capture your last point as well.

**Comment by katrinheitmann** [comment]
I sure hope so. @aphearin, do you have an update on the current status?

**Comment by drphilmarshall** [comment]
OK, check out the new Table 7 in the [overleaf DC2 Plan](https://www.overleaf.com/read/jwbjvjnszkzf). Merging @cwwalter 's vision of a 1-month analysis group validation period after the (internal) release of the Run 1.1p/i DM catalogs at the Winter collaboration meeting with @jchiang87 's definition of "code freeze" means we are looking at freezing the image simulation codes and configurations, and the DM pipeline tasks and configurations, in mid-late January. Comments welcome on this schedule - if you think this is too tight, please do suggest ways to ease it.

Other things of note:
* cosmoDC2 gets a checkpoint, to avoid pilot error in the cosmoDC2 run
* Truth Tables and Validation Suites now recognized as products in their own right.
* There's a 2-week gap between the DC2 checkpoint, and the expected completion of the cosmoDC2 Extragalactic Catalog - we should probably think of this as schedule contingency...

**Comment by jchiang87** [comment]
I think a mid-January date for the SSim code freeze may be too aggressive unless we are willing to live without certain features in imSim for DC2.  We should check with the people doing the implementations of the PSF and sensor effect features, but I would be surprised if those items would be ready before the end of January at the earliest.  I'm not sure where to find the time, but the 5 weeks between DR1.1 (02/07) and the DC2 Checkpoint (03/15) looks likely.

**Comment by drphilmarshall** [comment]
Would that mean planning for a DR1.2 (that simply remade the Run 1.1i
images and DM catalogs using the new ImSim features), after re-freezing the
SSim code? I guess the ImSim code would need to be finished c. 3 weeks
before the checkpoint (to leave time to make the Run 1.2 images, process
them, and run the validation tests) - so that'd be about 2/22 or so.

**Comment by drphilmarshall** [comment]
OK, I didn't add a Run 1.2 in between DR1.1 (at the winter meeting) and the DC2 Checkpoint explicitly, but instead pointed out that "additional test runs may have been carried out" in the 5 weeks following DR1.1. Here's the tex:  
```tex
\textbf{DC2 Checkpoint}            & \textbf{03/15/2018} & c.\ 1 month after DR1.1, during which
 additional test runs (1.2, etc) may have been carried out (to explore new features added since the
 Run 1.1 code freezes. We will review 1) the DC2 survey paper design section, 2) all validation tests
 on Run 1.x data, and 3) all inputs and pipelines. If all tests pass, tag simulation pipelines, decide
 PhoSim/ImSim balance  and start DC2 production (Run 2).\\
```

Are you happy with this timeline and these milestones, @cwwalter ? Should we move Table 7 up to the Executive Summary, to make sure everyone knows when things need doing by?

**Comment by cwwalter** [comment]
> Are you happy with this timeline and these milestones, @cwwalter ? Should we move Table 7 up to the Executive Summary, to make sure everyone knows when things need doing by?

@drphilmarshall and I discussed in person this afternoon.  I will put a reduced table in the executive summary focused on the users of the datasets rather than the the people producing them like the more extensive table 7.  I am still checking some details of table 7 with others.

**Comment by salmanhabib** [comment]
I am worried about several aspects of the Table 7 timeline. It doesn't look realistic to me considering that we are already behind on several tasks (e.g., 8.1.2 far from done, yes?). Is there an actual to-do list for people that goes along with Table 7 so we can tell who is supposed to do what and by when? The task descriptions (not obvious from milestone names at least to me) are not written up in the main document (presumably Section 8.X?). Should they be? 

Please tell me I don't have to worry and everything is awesome ;-).

**Comment by yymao** [comment]
I share similar concern to Salman's. On the CS side, for example, while we did make much progress on the validation tests, I am not sure if we'll have a suite that is sufficient to warrant CS code freeze on 1/26.

**Comment by drphilmarshall** [comment]
I *think* it should be possible to make the to-do list we're after in the
form of an epic issue for each item in Table 7 - the reason for making the
Table was to get a rough sense of when each thing would need to be
delivered. The schedule is driven by wanting to get DC2 Run 2 (the main
production run) done in time for the summer collaboration meeting: there's
a bit of contingency there, but not much.

Yao: when do you think cosmoDC2 production will actually be able to start,
if not 1/26?

Salman: what's the unrealistic part about January? Getting Run 1.1 finished
by the collaboration meeting? Notice that Run 1.1 is not designed yet, so
there's some flexibility there.

More generally, Run 1.1 is predicated on wanting to have data to look at
together at SLAC in February. If that is not the best use of our
collaboration meeting time, we can do something else!

**Comment by evevkovacs** [comment]
The main pieces missing from the validation tests are validation criteria for each of the tests (ie are the catalogs meeting the requirements). For this, we need feedback from the working groups. We are continuing to develop more tests, and as these become available, more criteria will have to be set by the WGs. We have a XWG session planned for February meeting on this topic, but if DC2 production code is frozen on 1/26, any further feedback from the WGs will be too late to impact DC2 production.  So there is mismatch here in terms of the timing. 
Overall, the schedule is quite aggressive. The time allowed for cosmoDC2 production is not generous, and we are currently evaluating exactly what we can deliver within that time frame (ie what combination of Galacticus runs + GalSampler is the best option)

**Comment by yymao** [comment]
@drphilmarshall: Seconding @evevkovacs's point --- we need WGs' input to finalize the validation criteria and at this moment, I don't feel they'll be ready by 1/26.

Also, if we decide to use GalSampler for the production of cosmoDC2 (which will save some production time), we should first validate a GalSampler version of protoDC2 to make sure we meet all validation criteria. 

In short, I think there are a few items on the to-do list for the 1/26 CS Code Freeze:
- [ ] Finalize the set of *required* validation tests
- [ ] Implement all required validation tests
- [ ] Finalize the validation criteria of all required validation tests
- [ ] Deliver a GalSampler protoDC2 catalog for validation 
- [ ] Approve that GalSampler meets our validation criteria, or if not, improve the algorithm until it does.

I might be on the pessimistic side but finishing all these items before 1/26 seems difficult (but I am happy to be pointed out that I am wrong!).

**Comment by drphilmarshall** [comment]
Thanks @yymao , thanks @evevkovacs ! Most helpful. Sounds like a better schedule could be to have the cosmoDC2 checkpoint (AKA the "CS Code Freeze") at the SLAC meeting, and then start cosmoDC2 production right after that successful review. That would get you an extra 2 weeks in January. The cosmoDC2 production time is an issue though: we can't start DC2 Run 2 production until the cosmoDC2 extragalactic catalog is made, which would be mid-April in this more relaxed timeline. I'm happy to make those edits, I just want everyone to know the implications. Obvs if we can claw back some time by using GalSampler that would be great.

This discussion is convincing me that we should translate Table 7 into a set of GitHub milestones and epics ASAP: we can spin out the detailed discussion into those issues, and also start assigning deliverables to people so we know who is responsible for delivering what - and as circumstances evolve, we can edit the milestones to reflect reality. @awborgland has a nice script for visualizing progress on GitHub milestones, which should keep an eye on our targets.

How about we do that Friday afternoon, after the talk? Milestone-making is Mgmt work, so maybe @katrinheitmann you could work on that, with Anders, as a service to the DC2 community? :-)

**Comment by fjaviersanchez** [comment]
@katrinheitmann @drphilmarshall I added several tables to the planning document showing the different validation tests that I could come up for different stages of the image generation process and I added a deadline for the Run 1.1 validations. My to-do list is:
- [] Contact DM to see if the QA scripts have been fully ported to LSST.
- [] Add basic validation scripts to Validation folder.
- [] Add issues/progress to the different tables in the planning document.

**Comment by katrinheitmann** [comment]
@fjaviersanchez Thanks Javier! This looks like a very good start. You did add this to the overleaf document, right? (@drphilmarshall: I still find it MUCH easier to use that instead of github ... but not sure if you from time to time just want to import it into the repo? Or if you want to close down the overleaf version all together?) One question: can you just use the same test set-ups for the instance catalogs that are in DESCQA already? I mean N(z) for example better not change from the extragalactic catalog to the instance catalog ... so I would think that you would use exactly the same test set-up with just a different input file? @yymao What do you think? In some sense, your instance catalog tests are not really validation tests but rather cross-checks that CatSim didn't do anything weird to the catalog, right?

**Comment by yymao** [comment]
@fjaviersanchez @katrinheitmann I think we can (and should try to) use DESCQA for catalog-level validation tests. We can implement readers for both the instance catalogs and for the final DM catalogs.

**Comment by fjaviersanchez** [comment]
@katrinheitmann I added several tables to the [overleaf document](https://www.overleaf.com/11393539dgxdcykvbqhm#/43020815/) (I hope I used the correct link)
@yymao I agree, we should try to use DESCQA at the catalog level whenever it's possible and I think that most tests that I wrote down in the tables are already implemented, so I guess that the main issue would be to generate a reader for these catalogs as you pointed out. @danielsf is [this](https://bitbucket.org/phosim/phosim_release/wiki/Instance%20Catalog) still the format of the instance catalogs or do we include more things? (like magnitudes in the different filters?)

**Comment by evevkovacs** [comment]
The N(z) and dN/dmag tests already exist and the ellipticity distributions are in progress. We are also writing a test that will display an arbitrary quantity, so much of the infrastructure you need is in place and should be usable (or adaptable) once the reader is available.

**Comment by drphilmarshall** [comment]
Thanks @fjaviersanchez ! I copied the `main.tex` file from overleaf and checked that this did not over-write anything in the current version, which is now back in GitHub - looks like we are OK! @katrinheitmann I think you can merge Javis commits in at https://github.com/LSSTDESC/DC2_Repo/pull/77  Then, we should make the overleaf document read-only, and shift to editing the DC2 plan by pull request on GitHub: this is better for mostly-stable documents. Can you take care of this please, as owner of the overleaf doc?

**Comment by danielsf** [comment]
@fjaviersanchez The link you pointed to is still the format for InstanceCatalogs that are going to be used as PhoSim inputs.  Truth tables including more information will have to be in separate files, as I do not think that PhoSim will respond well to us adding columns to its InstanceCatalogs.

**Comment by katrinheitmann** [comment]
I think this issue can be closed now. We do have a timetable and are working on items in that already. If we need more information to be included in the planning document, we should have a more specific issue. The validation tests for protoDC2 are tracked in a different repository.
