### ISSUE TITLE
Run 1.1 survey design: scale, fields, visits

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#72]
I was wondering how big Run 1.1 would be if we set ourselves a limit of 3 days CPU time, so I dug up @TomGlanzman 's rough PhoSim timing result that in steady state we can expect to be able to make something like 5-10 sensor visit images per KNL node-hour at NERSC, and extrapolated this to a strawman design for Run 1.1 to get us started. I figured we should try and do all filters, and enough fields and epochs to check that the image processing was working properly. [Here's an editable one-pager](https://docs.google.com/presentation/d/1Tu568VX9nDeMh_ED3Dk7ZCCEkjwW3fnPLQY8FaZgrao/edit#slide=id.p), feel free to duplicate the slide and try iterating it - or just drop your thoughts in a reply to this thread. For those who just want to see my working and comment, here's a PNG:

![image](https://user-images.githubusercontent.com/710903/34700163-66a06326-f496-11e7-9c14-972f5a73ff63.png)

@katrinheitmann Tom pointed out to me that wait times to get 500 nodes up and running are around 1 week, hence the footnote about needing to allow 2 weeks to make the Run 1.1 images.

**Comment by sethdigel** [comment]
The time estimates look consistent with Tom's posting on Dec. 21 [here](https://github.com/LSSTDESC/DC2_Repo/issues/65), actually a bit more conservative.  His ~270 minutes (clock time with 8 threads) per sensor visit scales to about 7.5 sensor visits per node hour vs. the 5 sensor visits per node hour that you are assuming.

**Comment by drphilmarshall** [comment]
@sethdigel Tom advised me to budget for about 30% extra time needed even in steady state, to cope with various submission inefficiencies. I'm fine with a conservative estimate: I was pleasantly surprised that 750 full-frame main survey visit images plus 750 4-raft uDDF visit images could be made in 3 days CPU time.  @jchiang87 @salmanhabib from a CI perspective, does this sound like a reasonable scale for Run 1.1? @cwwalter @fjaviersanchez do you see any SSim issues with the above design? Would you change anything about it - perhaps to get more value in the validation suite development?

**Comment by sethdigel** [comment]
Thanks, Phil.  Some dumb questions (that I did not find answers for in the dc2-planning-document):
What is the relation between the area of sky covered in Run 1, Run 1.1 (p/i), and Run 2?  Is the idea that they overlap?  Does Run 1.1 include the Run 1 data?  And Run 2 include Run 1.1 data?  I guess probably not.  Run 1 visits seemed to be centered more or less around RA, Dec = 0, 0, but I guess the actual field center for DC2 is still up for discussion.

In the planning document, the UDF is described as being made up of 3-raft images in a corner of the main survey region; what you are diagramming above has 4-raft images for the DDF more or less in the center of the Run 1.1 survey region.  So there will be a big evolution for Run 2?

**Comment by drphilmarshall** [comment]
My workflow is: sketch on gslides -> community feedback -> document in the Plan :-)

I'm not sure what sky area is being attempted in Run 1.0, but I know there is no uDDF component. I figured I'd start from a sensible 3-day CPU time constraint for Run 1.1 (that would keep us nimble, in case we need to re-do it), and see what area / campaign length that gave us. In the design above, the amount of imaging generated comes to about 2% of the full DC2 survey, which seemed to be about right in terms of a test run that gets us ready to produce at scale. 

I don't think we should plan on the Run 1.1 images being science-ready: there will probably be issues with them that need resolving, and they may well be feature-incomplete. We know that ImSim does not yet have all the features we need, and the instance catalogs may also be incomplete, if the sprinkler is not fully ready, the AGN have not been added, etc etc. If our goal is to have Run 1.1 data to look at together at the SLAC meeting, there are bound to be corners that have to be cut.

The uDDF field center was discussed in #71 and #54 - no-one has objected to it being the Twinkles field center, so I think we should go ahead and use that. (It's the center of a deep drilling field in `minion_2016`, so gives us all the OpSim visits we need. The protoDC2 galaxy positions will need to be offset to the DC2 field center though - that's a task that needs issuing, and the instance catalogs will need verifying to make sure we've done our trigonometry correctly!)

Re: 3 vs 4 rafts. Originally I tried drawing 3 rafts, and then dithering and rotating them: as you can imagine, the result is a lot more inefficiency from successive images failing to overlap each other, as they camera rotates. 4 rafts makes a more symmetrical field, with less wasted sky. Its more sensors than the 27 in the plan though, I agree. An alternative could be to ignore the 3 sensors in the far corner of each of the 4 rafts in my square: that would give us 6*4 = 24 sensors per DDF visit, in a more circular configuration. If we didn't mind simulating partial rafts, this could be a good way to go. Here's a picture of the three options I just described:

![image](https://user-images.githubusercontent.com/710903/34751398-3c5031ca-f561-11e7-88fa-d1b8bb8a0986.png)

How hard would it be to simulate the DDF sensor images in the diamond configuration, @cwwalter ?

**Comment by drphilmarshall** [comment]
Oh - and @sethdigel yes, the big evolution to Run 2.0 would be to add 27 more full fields out to the South and East of the Run 1.1 area (for example), and then do the remaining 7-8 years of visits.

**Comment by katrinheitmann** [comment]
@jchiang87 @salmanhabib We would like CI to sign off on this (see Phil's question above if the scale is reasonable from a computing perspective), can you take a look please and give us a "thumbs up"? For SSim, @cwwalter and @fjaviersanchez Phil wanted to make sure that this set-up rich enough in features to be a good test? If we can get a thumbs up from you as well we can push this to the next step. Thanks!

**Comment by jchiang87** [comment]
3 cpu days for Run1.1 seems like a reasonable scale to me.  However, since we can and are planning to run the simulation codes for individual sensor visits, rather than picking 3-4 rafts to simulate for uDDF and suffering from inefficiencies at various locations in the uDDF, we can instead pick a fixed region on the sky and just simulate whatever sensors fall within that region for a given visit, regardless of their parent raft.   That's essentially what we intended for Run1.0:  we had a 5x5 degree protoDC2 field and the phosim pipeline was designed to simulate only those sensors with more than minsource(=100) objects falling on the sensor.

**Comment by drphilmarshall** [comment]
@jchiang87 Oh, nice: I didn't realize we could do that! In that case, we could we set the uDDF area to be a square region measuring 5*4096 pixels on a side (a bit more than 68'), oriented N-E.  This is the same area as 25 sensors, so comparable to the original 3-raft scale. The images would be processed as 25 patches (if we go with 4096 pixel patches) in a 5x5 mosaic. This approach would lead to a fair amount of additional area being imaged, in the parts of the sensors landing outside the target region - but maybe this is OK, as it will provide a deep view of the square annulus around the uDDF, which ought to be useful for things like WL calibration. I'm not sure how much extra simulation /processing cost that would bring though - with the minsource=100 setting, do you get sensors that cover at least 10% of the target region?  50%?

**Comment by jchiang87** [comment]
Typical object counts I've been seeing in single sensor instance catalogs have been ~70k objects.   So at minsource=100, we'd get sensors with as small as ~14% coverage.

**Comment by drphilmarshall** [comment]
Thanks - that means that we'd end up simulating about twice as much area as was in the uDDF region. At each epoch, a DDF visit would involve simulating 25+24*(1-0.14) = 46 sensors (on average). This is 28% more sensor images than in my v1 strawman design, so at fixed cost we'd need to reduce the number of DDF epochs from 750 to 586. I am sure this will be plenty for the Run 1.1 test: @rbiswas4, which particular set of 586 DDF visits we use is up to you! I'll attempt an updated sketch of this scheme - thanks Jim.

**Comment by drphilmarshall** [comment]
Here we go: does this make sense?
![image](https://user-images.githubusercontent.com/710903/34892361-d8223db8-f78d-11e7-8776-c517219194b8.png)

**Comment by cwwalter** [comment]
> @cwwalter @fjaviersanchez do you see any SSim issues with the above design? Would you change anything about it - perhaps to get more value in the validation suite development?

One concern I have is that I suspect one of the things that is either going to go wrong or we are going to have work getting the processing to work properly is the overlap between the WFD and the uDDF regions.  In Run 2 it will be off at the edge but here we have it overlapping the all of the fields somewhere.  I think it might be better if we either at least shifted it to be over one FOV or (if we could spare the time) make another FOV separated in space from this one with the uDDF in the middle.  This way we can learn how that overlap works and how to deal with it while still getting the maximum area of "pure" WFD.  What do you think?

BTW @jchiang87 I know these #s will change because of the current imSim sky background work, but what kind of scaling should we be using for planning for the imSim run relative to Phil's numbers above from Tom for PhoSim with optimization? Would 1 to 1 be a conservative estimate (I'm not sure since I don't know the KNL scalings)?

**Comment by drphilmarshall** [comment]
@cwwalter I guess with the way sensors are selected, we can put the uDDF right in the corner of the main survey field and it should be fine... Happy to try that. I don't have an opinion about which corner the uDDF should go in: if @humnaawan and @egawiser have a suggestion for which direction the Run 2 main survey should extend to (NE? SW?) then that could help determine which corner we choose. 

![image](https://user-images.githubusercontent.com/710903/34894998-805d13d6-f798-11e7-8ad6-c82a2962cbe6.png)

**Comment by jchiang87** [comment]
@cwwalter Are you referring to the sensor model/sky background work?  That's a more complicated discussion which we should have elsewhere.

**Comment by cwwalter** [comment]
Yes.  I mean I know the time will go up with that work (which is as you say is not a discussion for here) but I was wondering if we already knew enough to get a sense of how long the same number of jobs as discussed above will take. 

Perhaps a better questions for here is the following: as a a low end estimate do we know the number on KNL without the sky background being routed through the sensor?

**Comment by katrinheitmann** [comment]
@drphilmarshall @rbiswas4 @humnaawan @egawiser: Below is a check list/message from Jim -- can you get this filled out/finalized and report on everything during the Friday telecon?
- [ ] WFD opsim db, i.e. minion_1016...new_dithers.db
- [ ] opsim db file with uDDF visits (this is another file right? the part has never been clear to me)
- [ ] the WFD field to simulate: This could either be opsim db FieldIDs as we did for DC1, or the four corners of the protoDC2 field rotated to the desired sky position.
- [ ] the uDDF field to simulate: I guess here we need the four corners.
- [ ] Anything else?
Once we have the above four items, I think we have enough info to generate the visit list and the instance catalogs.

**Comment by rbiswas4** [comment]
@katrinheitmann WFD opsim db and uddf visits are usually part of the same file: The schema has a column whether a row is a WFD or DDF observation (in cases where they play both roles, we are treating it as WFD). But I think I would also like to keep these separate at  this development stage, life would simply be easier. We can put them together later.

I might have missed it, but is there a statement on how the WFD field geometry should look for the final 1.3 run?

**Comment by drphilmarshall** [comment]
@rbiswas4 According to Jim above, we can define a sky region, and then just simulate the dithered sensors that fall in it. We can do this for Run 1.1 and Run 2, and for the DDF visits as well as the WFD. So, for Run 1.1 we just need to define two sky regions: I made a [concrete suggestion above](https://github.com/LSSTDESC/DC2_Repo/issues/72#issuecomment-357352548), two square fields. @humnaawan @egawiser does it matter which direction we extend in, out from the Twinkles field at RA: 03h 32m 30s Dec: -28d 06m 00s ? I drew the "main survey" region out to the SE - for Run 1.1 I expect this should be OK, but I'm less sure whether this is the right choice for Run 2. I guess we can always choose a different direction in Run 2, I just thought it'd be nice to, well, start out in the right direction :-)  Great if you can provide the coordinates of the 4 corners of the Run 1.1 main survey region (the big square) and then the coordinates of the 4 corners of the Run 1.1 uDDF (the small square).

@jchiang87 Before we make the visit list, we'll need to apply the dithering. @humnaawan @egawiser are we ready to apply chip-scale (half-chip?) dithers to the DDF visits? Do you suggest we over-write the dithered RA and Dec in a copy of Rahul's opsim db, or add a new column that is only non-zero for DDF visits?

**Comment by rbiswas4** [comment]
@drphilmarshall in principle, we don't need to know how the WFD field geometry will look to define 1.1. Because as you say we could do it different. But again, as you said, it would think ahead if we can. 


Relevant to the other comment meant for @humnaawan @egawiser @jchiang87 : I am rewriting the ditheredRA, ditheredDec in the WFD opsimdb (so this changes the depths) with dithers from @humnaawan  file ... this jives with @drphilmarshall 's first suggestion... since we have decided which dithers to use, this seems simple rather than the other possibility of adding new columns (@drphilmarshall 's alternative suggestion). However, if you have reasons to choose @drphilmarshall 's second suggestion of adding a new column, it would be good to do this for the WFD visits as well (and these will not be non-zero for only DDF).

**Comment by jchiang87** [comment]
@rbiswas4 Here is the code where the dithering information from the opsim db file that had been modified to include dithering for DC1, i.e., `minion_1016_sqlite_new_dithers.db`.  As you can see, the columns being used are `randomDitherFieldPerVisitRA`, `randomDitherFieldPerVisitDec`, and `ditheredRotTelPos`.  We should use the same column names for DC2.  I think we have already stipulated that we would use `minion_1016_sqlite_new_dithers.db` for WFD, correct?  So we only need a uDDF opsim db with the desired columns.

Regarding the WFD field for Run1.1, I think we have agreed that we are using the protoDC2 field rotated to our desired location.  That will set the maximum size of the WFD field to 5x5 degrees.   Scott has added code to `sims_GCRCatSimInterface` to do the rotation from RA, Dec = 0, 0 to our desired location, but I don't think it sets the orientation of the protoDC2 field.

**Comment by egawiser** [comment]
A few replies, working backwards:  @jchiang87 we can discuss on Friday, but @humnaawan and I were thinking it's safer to add new columns that contain the desired RA,Dec,Rot dithers and can be used for both WFD and uDDF visits; they could be named e.g., finalDitherRA, finalDitherDec, finalDitheredRotTelPos.  For WFD, we'd copy the existing info into those new columns.  For uDDF, we can generate smaller random dithers for RA,Dec if @rbiswas4 or @drphilmarshall tells us the maximum dither value to allow.  For uDDF, we'd copy the undithered RotTelPos into finalDitheredRotTelPos, since our impression is that we don't want to rotationally dither the uDDF observations.  If for coding reasons it's better to use the same opsim db column names as in DC1, then we'd do the same overwrites in those, but it might be harder to figure out the history of how the values were generated.

**Comment by egawiser** [comment]
@humnaawan is working to define "rectangles" for uDDF, Run1.1, and Run 2.0.  All of these will be square in real degrees, stretching South and East from the CDF-S field center i.e., Twinkles field at RA: 03h 32m 30s Dec: -28d 06m 00s (with those coordinates placed at the center of a 68.0x68.0 arcminute square for the uDDF - could you please confirm that, @drphilmarshall?).  We looked at a minion1016 r-band depth map and it looked fine to go South and East, but Humna will confirm that doing so yields reasonably uniform and typical depths in all filters.  Humna will then generate a list of hexagonal fieldIDs whose dithered WFD visits fall within the desired rectangles, and the rectangles can be used to trim the instance catalogs (with a variable buffer allowed for bright stars, at least in Run 2.0 and possibly in Run 1.1).

**Comment by rbiswas4** [comment]
@jchiang87 @egawiser @humnaawan 

I am happy to follow any column names for dithers that you can decide (Would it be ok to suggest `finalDitheredRA` or `randomDitheredFieldPerVisitPerRA` to make it clear that this is the dithered value, not the dither that should be added to the original to get the dithered value). 

@jchiang87 @egawiser : So, I think we have everything that is necessary for WFD the columns that are changing or being added from the original are depths, and dithers. The depths don't really affect the simulation, but are following @jchiang87 suggestion of freezing the opsimdb for catalog analysis as well. 

@egawiser I think from the SN point of view, we would like small dithers on the uDDF region. However, we don't want this to be terribly unnatural. It seems having a chip size dither means a loss of sources in  the perimeter chips: in the square that would be 20 chips lost (to about 50 percent say?) of the 36. The number lost in the L shape is 21. Does this counting make sense? @drphilmarshall Maybe we want to restrict the dithers to 0.5 chips?

**Comment by jchiang87** [comment]
I don't think we can check off the WFD opsim db box.  There is a proposal on the table to add `finalDithered*` columns to the that file.  Once that file is modified, it needs to be renamed and is a **new** opsim db, even if most of the columns are unchanged.

Regrading the column names:  I'm ok with adding the `finalDithered*` columns and using those, but I would like us to establish a convention that we maintain hereafter.  We will no doubt be doing this again, so I'd like to avoid changing the interfaces to the needed data every time.

**Comment by drphilmarshall** [comment]
Looking at the suggestions above, how about:
```
descDitheredRA
descDitheredDec
descDitheredRotTelPos
```
i.e. close to @egawiser 's proposal but with @rbiswas4 's sensible past tense. I'm not a huge fan of "final" (it seems certain to  need to be replaced one day with "finalFinal") - so maybe "desc" is a better prefix, indicating that "DESC dithering" was applied.

I think restricting the DDF visit dithers to 0.5 chip widths sounds good.

**Comment by egawiser** [comment]
Above comments from @rbiswas4 @jchiang87 and @drphilmarshall sound sensible to me.  For the uDDF dithering, you only really need to dither by the width of the chip gaps, yes?  You can ask for the maximum dither amplitude to be as small as you want, but note that the typical dither is smaller than that maximum by roughly a factor of 2, so the maximum should be at least twice the width of the chip gaps (and perhaps a maximum of 0.5 chip would work fine).

**Comment by rbiswas4** [comment]
When the SN group was discussing dithers the two things that came up mostly from @saurabhwjha were the need to get a contiguous image (the chip gap), and an uncertainty in pointing (but the other one hopefully dominates).

  
So, if I am reading the numbers correctly: 
1 pixel ~ 10 mu m ~ 0.2 arc sec. 
1 chip-gap ~ 250 mu m, So, min dither (see statement from @egawiser): ~ 500 mu m = 50 pixels ~ 10 arc sec. 
1 chip ~ 4k pixels = 4e4 mu m ~ 100 * 2 *chip gaps 8 e2 arc sec.

Note, there is a good reason to keep it >~ 10 arc sec, the 0.5 chip estimate was about minimizing losses that increase with dithers. Keeping it low means we minimize losses.

max dither based on 2* chip gap to 0.5 chips has the range :  10 arc sec - 800 arc sec . So, maybe we should go towards the lower end of the range say 50 arc sec rather than higher? What might drive us to the higher end during the real survey?

**Comment by drphilmarshall** [comment]
While we wait for wisdom from DM on how large/small the DDF visit dithers should/can be, I adapted our checklist into the [slides for Friday](https://docs.google.com/presentation/d/1r5CQM1zkL7uYr8w8ExQYKiPtfSW4Z94O35IcBNqnI0o/edit#slide=id.g2ef820c458_0_143). @rbiswas @humnaawan can I leave this slide with you to edit and report on please? Ideally, once each piece is made and delivered (somehow), we'd turn the text for that item green. "Delivery" means providing the URL (or NERSC filesystem address) of the product. An online document would work - I'll see about getting a Run 1.1 Note started.

**Comment by katrinheitmann** [comment]
Started one here: 
https://docs.google.com/document/d/1aQOPL9smeDlhtlwDrp39Zuu2q8DKivDaHLQX3_omwOI/edit

**Comment by rbiswas4** [comment]
@drphilmarshall Thank you! will edit those.

**Comment by drphilmarshall** [comment]
Following discussion on Slack about how the protoDC2 catalog ends up rotating on the sky in  order to be translated into position, here's an updated design sketch showing this rotation. We also said on Slack that the uDDF might as well be at the center of the field for Run 1.1, so we don't have to spend time fiddling with offsets to get it into the corner of the main survey. All will be cleaner in Run 2.0 when cosmoDC2 is positioned on the sky from the outset.

 
![run 1 1 strawman survey design](https://user-images.githubusercontent.com/710903/35123960-2e003314-fc59-11e7-92d2-8f2a7e70dffa.png)

**Comment by cwwalter** [comment]
@egawiser can you clarify one thing that was discussed as an option a while ago:  Will there be separate columns for the uDDF dithers.  Or will there just be one set of column with the appropriate dithers applied for each visit?

**Comment by sethdigel** [comment]
Does the uDDF need to be square?  Rather than think of it as a ~5x5 grid of sensors (each spanning ~13.3'), it could be a region with a radius of 3 sensors (40') and have about the same area.  At least in terms of rotational dithering the same sensors would always be relevant no matter the rotation and 21 sensors (arrayed like the 21 rafts of the LSST focal plane) would always be entirely within the region.  Since the plan is to have phoSim simulate only the sensors that have more than some minimum number of sources shining on them, it is probably worthwhile thinking of the uDDF as circular anyway, so it won't have corners with lower depth of coverage.

**Comment by egawiser** [comment]
@cwwalter we appear to have decided on just one set of (three) added columns (whose names start with desc and were noted in today's telecon slides) that work for both WFD and uDDF visits.

**Comment by egawiser** [comment]
@sethdigel this is a really helpful suggestion.  It's not clear to me that it matters much what shape we assign to the uDDF region that gets time-domain sources sprinkled onto it.  We'll be dithering the focal plane both translationally and rotationally, and simulating any sensors that have modest overlap with the uDDF region.  So it's a subtle question of overlap efficiency between randomly placed, rotated squares (the sensors) and the border geometry of the region.  Probably circular is the most efficient, but my guess is it's a small effect.

**Comment by rbiswas4** [comment]
Since many of the discussions are running on other issues, I would like to make sure I have the current version of the plan and status on these topics. So, I would like to have a checklist (was not planning to edit Katrin's checklist earlier in the thread, but @katrinheitmann should feel free to put this there so that we have one checklist:

-  [ x] an opsim database with WFD and DDF visits without the columns for desc dithers
- [ x] sizes of positional and rotational dithers for WFD visits (done following DC1)  
- [ ] sizes of positional and rotational dithers for uDDF visits 
- [x] Dithered DC2 Run1.1 WFD (positional and rotational dithers added as new columns to show the dithers being used for DC2 for WFD. Done from DC1?) 
- [ ] Dithered uDDF : Dithered (positional and rotational dithers added as new columns to show the dithers being used for DC2 for uDDF according to the sizes chosen for DC2 (needs undithered DB, size of uDDF dithers).
- [ X] position of center of uDDF field : Twinkles field 
- [ ] Geometry of the uDDF field (square/circular : this determines the dithered uDDF visits that will overlap with the uDDF field, there might be visits that have small ) 
- [ ] Location and geometry of protoDC2
- [ ] Visit lists overlapping WFD (needs Dithered DC2 Run1.1 WFD, location and geometry of protoDC2)
- [ ] Visit lists overlapping uDDF (needs dithered uDDF,  position of center of uDDF , Geometry of uDDF field) 
- [ ] (not science but processing) Interest in partially overlapping visits for uDDF 
- [ ] WFD Visit Lists for Run 1.1 
- [ ] uDDF Visit Lists for Run 1.1
- [ ] Keep location link and states of products in github repository
- [ ] location of these products on NERSC (currently I put them on /global/cscratch1/sd/rbiswas/opsimdb/DC2/, but I recall the discussion but not the result, and want to make sure things are readable by all)

**Comment by drphilmarshall** [comment]
At the DC2 meeting we discussed the possible need for the uDDF region to be circular, and whether it should be in the corner, rather than the center. In the spirit of using Run 1.1 to flush out bugs, I propose we keep the square field but return to the corner placement. I will update the specs note with new coordinates for the protoDC2 center (that put the uDDF in the corner) and paste in a slightly updated figure:

![run 1 1 strawman survey design](https://user-images.githubusercontent.com/710903/35230810-f79851a8-ff4b-11e7-9d1c-beef40159ea8.png)

Once we have these cooordinates, we'll need @danielsf to apply the new protoDC2 rotation, and then @humnaawan and @rbiswas4 to work out the visits. Thanks!

**Comment by katrinheitmann** [comment]
@drphilmarshall and @rbiswas4: Now that we have the DESC Note on this, can we close this issue? Thanks!

**Comment by drphilmarshall** [comment]
I think so, yes! It looks to me as though everything on Rahul's list could be checked off, too - so I'll close this. Thanks for cleaning up!
